"use client";

import { Amplify } from "aws-amplify";
import outputs from "@/amplify_outputs.json"; // This file is generated by 'npx ampx sandbox'
import { Authenticator } from "@aws-amplify/ui-react";
import { StorageBrowser } from "@aws-amplify/ui-react-storage";
import "@aws-amplify/ui-react/styles.css";

// Configure Amplify immediately
Amplify.configure(outputs);

export default function Home() {
  return (
    <Authenticator>
      {({ signOut, user }) => (
        <main className="flex min-h-screen flex-col bg-gray-50">
          {/* Header */}
          <header className="sticky top-0 z-20 w-full bg-white border-b shadow-sm">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center text-white font-bold">S3</div>
                <h1 className="text-xl font-bold text-gray-900">Storage Browser</h1>
              </div>

              <div className="flex items-center gap-4">
                <div className="text-sm text-gray-600 hidden sm:block">
                  <span className="opacity-70">Signed in as</span> <span className="font-medium text-gray-900">{user?.signInDetails?.loginId}</span>
                </div>
                <button
                  onClick={signOut}
                  className="px-4 py-2 text-sm font-medium text-red-600 bg-red-50 hover:bg-red-100 rounded-md transition-colors border border-red-200"
                >
                  Sign out
                </button>
              </div>
            </div>
          </header>

          {/* Main Content */}
          <div className="flex-1 w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div className="bg-white rounded-xl shadow-lg border border-gray-100 overflow-hidden h-[calc(100vh-8rem)]">
              <StorageBrowser />
            </div>
          </div>
        </main>
      )}
    </Authenticator>
  );
}
